### ISSUE TITLE
Using serial port to connect CentOS pwsh I encountered a mistake.

### ISSUE THREAD

**Issue by he852100** [lzybkr/PSReadLine#754] opened 2018-08-28 06:21 UTC
[root@localhost ~]# pwsh
PowerShell v6.0.4
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /root> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

PS /root>

**Comment by lzybkr** [comment] 2018-08-28 17:46
This is probably a duplicate of #670.

**Closed as completed** 2018-10-17 16:24 UTC
